name: congresso_unama
description: Aplicativo desenvolvido com Flutter para exibir a programação dos congressos da Universidade da Amazônia - UNAMA.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# https://stackoverflow.com/a/56970752/2457045
# Version Number, Build Name: 1.0.0
# Version Code, Build Number: +1
version: 1.0.2+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  rxdart: ^0.22.3
  bloc_pattern: ^2.3.4
  
  firebase_core: ^0.4.0+7
  cloud_firestore: ^0.12.7
  firebase_crashlytics: ^0.1.0+3
  
  shared_preferences: ^0.5.3+4
  share: ^0.6.2+1
  cached_network_image: ^1.1.1
  url_launcher: ^5.1.6
  package_info: ^0.4.0+6
  google_maps_flutter: ^0.5.20+6
  flutter_custom_clippers: ^1.1.0
  admob_flutter: "^0.3.1"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  flutter_native_splash: ^0.1.8+2

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: assets/images/splash.png
  color: 4caf50

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700