name: Build app for Android and iOS

on:
  push:
    branches:
    - dev
    - master
    pull_request:
      branches:
      - dev
      - master

jobs:
  android:
    name: Build app for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: keytool -genkey -noprompt -v -keystore ./key_githubactions.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key -storepass githubactions -keypass githubactions -dname "CN=githubactions, OU=githubactions, O=githubactions, L=githubactions, S=githubactions, C=githubactions"
      - run: echo "storePassword=githubactions\nkeyPassword=githubactions\n\nkeyAlias=key\nstoreFile=./key_githubactions.jks" > ./android/key.properties
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk
      - run: flutter build appbundle
  ios:
    name: Build app for iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build ios --release --no-codesign
